# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(max_length=150)),
                ('key', models.ManyToManyField(to='back.Article')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
